name: SCChatManager
version: 2
api-version: 1.16
main: ru.vadimka.chatmanager.ChatManager
author: Vadimka
commands:
  chmreload:
    description: Перезагружает плагин
    usage: /<command>
  chr:
    description: Команта комнат
    usage: /<command>
permissions:
  chatmanager.*:
    description: Все преимущества плагина
    default: op
    children:
      chatmanager.reload: true
      chatmanager.adminchat: true
      chatmanager.color: true
      chatmanager.room.*: true
  chatmanager.reload:
    description: Перезагружает плагин
    default: false
  chatmanager.adminchat:
    description: Получать и отправлять сообщения в админ-чат
    default: false
  chatmanager.color:
    description: Писать в чат цветом
    default: true
  chatmanager.room.*:
    description: Все преимущества комнат
    default: false
    children:
      chatmanager.room.roster: true
      chatmanager.room.list: true
      chatmanager.room.roster.other: true
  chatmanager.room.list:
    description: Спсок комнат
    default: false
  chatmanager.room.roster:
    description: Возможность просматривать список пользвоателей в своей комнате
    default: false
  chatmanager.room.roster.other:
    description: Возможность просматривать список пользвоателей в комнате
    default: false